site_name: My Music
theme:
  name: material
  language: pt-BR
  logo: ../../Assets/LogoMyMusic.png
  favicon: ../../Assets/LogoMyMusic.png

  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra 


nav:
  - Sobre o projeto: index.md
  - 1. Base:
    - 1.1. Módulo Projeto Não Orientado a Abordagens Específicas:
      - 1.1.1. Design Sprint: Base/Design Sprint.md
      - 1.1.2. Técnicas de Elicitação:
        - 1.1.2.1. Brainstorming: Base/brainstorming.md
        - 1.1.2.2. Entrevista: Base/entrevista.md
        - 1.1.2.3. Questionário: Base/questionario.md
      - 1.1.3. Artefatos Independentes:
        - 1.1.3.1. Glossário: Base/glossário.md
        - 1.1.3.2. 5W2H: Base/5w2h.md
        - 1.1.3.3. Léxico: Base/lexico.md
        - 1.1.3.4. Rich Picture: Base/richpicture.md
        - 1.1.3.5. Mapa Mental: Base/mapa_mental.md
      - 1.1.4. Protótipo: Base/prototipo.md
    - 1.2 Módulo Processos/Metodologias/Abordagens: Base/ProcessosMetodologiasAbordagens.md
    - 1.3 Participações Base: Base/ParticipacoesBase.md
  - 2. Modelagem:
    - 2.1. Módulo Projeto Orientado a Abordagens Tradicionais: 
      - 2.1.1. Notação UML - Diagramas Estáticos:
        - 2.1.1.1. Diagrama de Classes: Modelagem/diagramaClasses.md
        - 2.1.1.2. Diagrama de Pacotes: Modelagem/diagramaPacotes.md
        - 2.1.1.3. Diagrama de Componentes: Modelagem/diagramaComponentes.md
      - 2.1.2. Notação UML - Diagramas Dinâmicos:
        - 2.1.2.1. Diagrama de Sequência: Modelagem/diagramaSequencia.md
        - 2.1.2.2. Diagrama de Atividade: Modelagem/diagramaAtividades.md
        - 2.1.2.3. Diagrama de Estados: Modelagem/diagramaEstados.md
    - 2.2. Participações - Modelagem: Modelagem/ParticipacoesModelagem.md
  - 3. Padrões de Projeto:
      - 3.1. Módulo Padrões de Projeto GoFs Criacionais: PadroesDeProjeto/GoFsCriacionais.md
      - 3.2. Módulo Padrões de Projeto GoFs Estrutural: PadroesDeProjeto/GoFsEstruturais.md
      - 3.3. Módulo Padrões de Projeto GoFs Comportamental:
        - 3.3.1. Strategy: PadroesDeProjeto/GoFsExtras.md
        - 3.3.2. Command: PadroesDeProjeto/GoFsComportamentais.md
      - 3.4. Participações - Padrões de Projeto: PadroesDeProjeto/ParticipacoesPadroes.md
      - 3.5. Iniciativas Extras: PadroesDeProjeto/IniciativasExtras.md
  - 4. Arquitetura de Software e Reutilização: 
    - 4.1 Módulo Estilos e Padrões Arquiteturais: ArquiteturaReutilizacao/estiloEPadroesArquiteturais.md
    - 4.2 Módulo Reutilização de Software: ArquiteturaReutilizacao/reutilizacaoDeSoftware.md 
    - 4.3 Módulo Arquitetura de Software:
      - 4.3.1 Arquitetura de software: ArquiteturaReutilizacao/arquiteturaDeSoftware.md
      - 4.3.2 Visões:
        - 4.3.2.1 Visão de Implantação: ArquiteturaReutilizacao/VisaoDeImplantacao.md
        - 4.3.2.2 Visão de Implementação: ArquiteturaReutilizacao/VisaoDeImplementacao.md
        - 4.3.2.3 Visão dos Casos de Uso: ArquiteturaReutilizacao/visao-casos-de-uso.md
        - 4.3.2.4 Visão de logica: ArquiteturaReutilizacao/visao-de-logica.md
        - 4.3.2.5 Visão de Processo: ArquiteturaReutilizacao/visao-de-processo.md
        - 4.3.2.6 Visão de Dados: ArquiteturaReutilizacao/visaoDados.md
    - 4.4 Participações - Arquitetura & Reutilização de Software: ArquiteturaReutilizacao/participacoesArqReutilizacao.md
  - Reuniões:
    - Ata 01: Atas/ata_1.md
    - Ata 02: Atas/ata_2.md
    - Ata 03: Atas/ata_3.md
    - Ata 04: Atas/ata_4.md
    - Ata 05: Atas/ata_5.md
  - Sprints:
    - Sprint Entrega 3:
      - Sprint Planning: Sprints/Sprint1/SprintPlanning1.md
      - Sprint Review: Sprints/Sprint1/SprintReview1.md
