// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPd-cXwZ4Q9ETsS8LmDvLZMQY0TYUyeRo',
    appId: '1:882298767238:web:53b6fdcda789e683c6ce07',
    messagingSenderId: '882298767238',
    projectId: 'mymusic-unbarqdsw',
    authDomain: 'mymusic-unbarqdsw.firebaseapp.com',
    storageBucket: 'mymusic-unbarqdsw.appspot.com',
    measurementId: 'G-LSRMHR8W04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoXPQ-KGTWxReD8TUIccsiUoKMyvcqwCc',
    appId: '1:882298767238:android:11ab3d1e36566c61c6ce07',
    messagingSenderId: '882298767238',
    projectId: 'mymusic-unbarqdsw',
    storageBucket: 'mymusic-unbarqdsw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDALRRHdLjwZ2oDQxnz0ZVRI91Y1Ai74CQ',
    appId: '1:882298767238:ios:16adcdcaefaf64c1c6ce07',
    messagingSenderId: '882298767238',
    projectId: 'mymusic-unbarqdsw',
    storageBucket: 'mymusic-unbarqdsw.appspot.com',
    iosBundleId: 'com.example.myMusicCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDALRRHdLjwZ2oDQxnz0ZVRI91Y1Ai74CQ',
    appId: '1:882298767238:ios:16adcdcaefaf64c1c6ce07',
    messagingSenderId: '882298767238',
    projectId: 'mymusic-unbarqdsw',
    storageBucket: 'mymusic-unbarqdsw.appspot.com',
    iosBundleId: 'com.example.myMusicCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPd-cXwZ4Q9ETsS8LmDvLZMQY0TYUyeRo',
    appId: '1:882298767238:web:8b25c53243bd25c4c6ce07',
    messagingSenderId: '882298767238',
    projectId: 'mymusic-unbarqdsw',
    authDomain: 'mymusic-unbarqdsw.firebaseapp.com',
    storageBucket: 'mymusic-unbarqdsw.appspot.com',
    measurementId: 'G-P3F4HS8BXX',
  );
}
